name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@v20

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
